#############################
#   General Configuration   #
#############################

# Debug : true/false
# Will print StackTrace to your console if an error occurs
# Will enventually print some messages in your console and/or chat of specified player(s)

debug :
    enable : false
    player : Dzious

# Language file that should be used
language : en_us.yml



##############################
#   Dungeons Configuration   #
##############################
dungeons: ["example"]